import { chromium } from 'playwright-core';
import { resolve } from 'node:path';
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args:['--no-sandbox','--force-color-profile=srgb'] });
const p = await b.newPage({ viewport:{width:1920,height:1080}, deviceScaleFactor:1 });
await p.goto('file://'+resolve(process.argv[2]));
await p.evaluate(()=>document.fonts.ready);
await p.waitForTimeout(200);
await p.screenshot({ path: process.argv[3], omitBackground:true });
await b.close();
console.log('overlay png', process.argv[3]);
